# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cartegory',
            new_name='category',
        ),
    ]
